### ISSUE TITLE
Search Misinterprets Special Characters

### ISSUE THREAD

**Issue by Ben-Brady** [VoidlessSeven7/Rule-34-App#65]
**Describe the bug**
`five_nights_at_freddy's` becomes encoded as `five_nights_at_freddy&#039;s`
This is because any special character such as the `'` in `five nights at freddy's` is transformed into HTML encoded.
Additionally, because these characters are misinterpreted, I believe the API lookup for their tag count also fails as well as post search.

**To Reproduce**
1. Go to Search
2. Search for the tag five_nights_at_freddy
3. See the broken tags

**Expected behavior**
The characters should be encoded as a regular character instead of html encoding.

**Screenshots**
![image](https://user-images.githubusercontent.com/64110708/154846148-4d1b9340-def8-496e-abb1-e34369b88eb5.png)
![image](https://user-images.githubusercontent.com/64110708/154846194-f0996ac9-c3a1-490a-a37a-b404e09d719d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser FireFox
 - Version 97

**Comment by AlejandroAkbal** [comment]
Yes, this is a long-standing bug.

From what I can see, the client side encoding is done wrongly.

It should be:
https://r34.app/?domain=rule34.xxx&page=0&tags=five_nights_at_freddy%27s

But it is
https://r34.app/?domain=rule34.xxx&page=0&tags=five_nights_at_freddy%26%23039%3Bs

Which the API does not understand.

I will try some fixes later, thank you for reporting it.

**Comment by AlejandroAkbal** [comment]
Fixed in the API.
