### ISSUE TITLE
Special Charater Tags Have null Count

### ISSUE THREAD

**Issue by Ben-Brady** [VoidlessSeven7/Rule-34-App#66]
**Describe the bug**
When searching for tags that include special characters, eg the `'` in `five_nights_at_freddy's`, the tag count is displayed as null

**To Reproduce**
1. Go to Tag Select
2. Search `five_nights_at_freddy`
3. Check tag count

**Expected behavior**
The tag count should be properly displayed as a number

**Screenshots**
![image](https://user-images.githubusercontent.com/64110708/158224867-e9648094-a562-4bb3-8fc7-842bc964d94b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Firefox
 - Version 98

**Comment by AlejandroAkbal** [comment]
Fixed.
It was a problem with a RegExp in our API.

Thank you for the report <3
